{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {},
   "outputs": [],
   "source": [
    "import io\n",
    "from google.cloud import speech\n",
    "from google.cloud.speech import enums\n",
    "from google.cloud.speech import types\n",
    "import os\n",
    "import google.cloud.speech_v1p1beta1 as speech"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [],
   "source": [
    "def transcribe_file_with_enhanced_model(path):\n",
    "    \"\"\"Transcribe the given audio file using an enhanced model.\"\"\"\n",
    "    \n",
    "    with io.open('/Users/jannes/Documents/GitHub/compliance-ai-source-code/complianceai-49c329bab220.json') as cred:\n",
    "        credentials = cred.read()\n",
    "        \n",
    "    print(credentials)\n",
    "        \n",
    "    client = speech.SpeechClient(credentials='/Users/jannes/Documents/GitHub/compliance-ai-source-code/complianceai-49c329bab220.json')\n",
    "\n",
    "    with io.open(path, 'rb') as audio_file:\n",
    "        content = audio_file.read()\n",
    "\n",
    "    audio = speech.types.RecognitionAudio(content=content)\n",
    "    config = speech.types.RecognitionConfig(\n",
    "        encoding=speech.enums.RecognitionConfig.AudioEncoding.LINEAR16,\n",
    "        sample_rate_hertz=8000,\n",
    "        language_code='en-US',\n",
    "        # Enhanced models are only available to projects that\n",
    "        # opt in for audio data collection.\n",
    "        use_enhanced=True,\n",
    "        # A model must be specified to use enhanced model.\n",
    "        model='phone_call')\n",
    "\n",
    "    response = client.recognize(config, audio)\n",
    "\n",
    "    for i, result in enumerate(response.results):\n",
    "        alternative = result.alternatives[0]\n",
    "        print('-' * 20)\n",
    "        print('First alternative of result {}'.format(i))\n",
    "        print('Transcript: {}'.format(alternative.transcript))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{\n",
      "  \"type\": \"service_account\",\n",
      "  \"project_id\": \"exploreinsstt\",\n",
      "  \"private_key_id\": \"49c329bab2209cfd61c58fd4ef9254ebc0c0e609\",\n",
      "  \"private_key\": \"-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDfaQ2yMFkniS6l\\nqK/cBhP/kijGJ8+6WhbSbBRyANI4GT/MqUX88uZOgVjGHgfKoq7uRGsSIdKzekB4\\nO1yzjw0MzhzY2O9HqOXugc8Ew/8JeHLzjg4Co3bAkjp9VMsFKuDNgiqZo42IDh7s\\nmYOlgNCinuEVraoPv/MLm+BRv2eTja9xWsDQnvU0Dn5SdkeTApyJOxo+s6/8f1OP\\nsmr5pgn6AWx2QqzFsdrX3BAXAEc8waZ4o30E8ax+BpBxGexzqxq1tfMhw736qS9K\\nU0u5ODthernywck3d7WzS8XcykOegZbcNMX6I9dFjXcCUK5O9+RX80t6uSUuQOEd\\nknR8gp0DAgMBAAECggEAIz1daTGCJp/XaU8J6lFVHzeNUfBerlzeg7ODqBXkEvA8\\npYo/3W3tEQ4LFDkRbo+puzC0mOgX5bKPb8ehUDtsygvK9hOF7s4/8pasMmq+FF7Y\\n9vz9zcG+DhMiwbk5yudgDVqOYKyxOvhLPXPblaQThMs94t8BV7ml2ztrr0lbS6U+\\nu4wiQfxEyoGWn1DHkz3Yr8+qCzvNPY6KULDLTpdbCyZSEw6uVumMhibflxtFjrFb\\nhmi+WcGxCzKaujWxDzioUd61gd/XALRqXspp1yx9FNqiCpA2S4adNGNrJp5fmedw\\ntLTmtfJZRjsIqm9cl6Y5ALAPpeuP74di1315DP62EQKBgQD4F/hwR8yVXBT72p1W\\nKLiDYG48ymWFEWqMNszxL9OuMoS65dJWl9OecSPp47lq5nwRZ8SnrEaGRZEgSZ/7\\nhCcH6cg51LJTrYwy+QW3BhkkABhF1xp84Gmkc9Frqyl/6P7diW+XL55jQSJw9wup\\nDLm5mbTPMYbRghMCPm0FKm2+MQKBgQDmh7Vz7pPGqGfUvLtEDYZQcQqIEeJCHQxj\\nBY/nL+VP6sReOSnV4skpxgoQL3dufwkqI8vIhLxELPO8x34FROjv4N20VXEudRjZ\\nH18S0ldJkag3h6gFFmkFRj92SbXoXZWUQpJhjJJ5Q+sRy5/6kp6h1iCpO8G9bQXB\\nesgPdYy9cwKBgQCJ6VFKoS8BzClCA7m4nnRLW7yMAHrEqPTQstnkLRD/4cdU2dK+\\nHjId/ojXSKbW3P8U8dko2CRwGZXeG+9Z8pF73aJXO3xR9cRcxX8+yZ4KHB9iG3v2\\n9QzkxRkiQAiWuR+MaQzmPytNw3Rw1XPe6lsH6IDROJfYOPV2JtuVpotQ0QKBgGPp\\npWcdm8aZ7oZxVehkxDXRCHN47Msis9+m5XuZcpV0dq8vr0YYCH+maW4iZGzrehld\\nclDx1nbl1K2Y+LFn8F0m5G/oKCmubpqL0jTiHRqxmmqWzOeHkvTKQW8O+1w+Uzny\\nsGa++iy8lwEbc7ayHTafC4DNeWaT/c6hXFv24oypAoGBAIqf5+RyJHO3ODSS7Bkb\\nFsJ/mT4ygky/OWx/Ptx/cYTmdIDvERnaIFpjI/trhfsGdTvH1ny/7+gnYaqvS3vb\\nuPrfh5DcFpi5dhgm5LWpqOQnQfD1Gd6beUeyJhZPDxOE98Q+fzZmckVQvhBZ7IeJ\\n0eQjKThWM/0V5kk4n+pdoHyd\\n-----END PRIVATE KEY-----\\n\",\n",
      "  \"client_email\": \"complianceai@exploreinsstt.iam.gserviceaccount.com\",\n",
      "  \"client_id\": \"117243308749499423696\",\n",
      "  \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\n",
      "  \"token_uri\": \"https://accounts.google.com/o/oauth2/token\",\n",
      "  \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\n",
      "  \"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/complianceai%40exploreinsstt.iam.gserviceaccount.com\"\n",
      "}\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x1128b9ac8>\" raised exception!\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/grpc/_plugin_wrapping.py\", line 77, in __call__\n",
      "    callback_state, callback))\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 77, in __call__\n",
      "    callback(self._get_authorization_headers(context), None)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 61, in _get_authorization_headers\n",
      "    self._credentials.before_request(\n",
      "AttributeError: 'str' object has no attribute 'before_request'\n",
      "ERROR:root:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x1128b9ac8>\" raised exception!\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/grpc/_plugin_wrapping.py\", line 77, in __call__\n",
      "    callback_state, callback))\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 77, in __call__\n",
      "    callback(self._get_authorization_headers(context), None)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 61, in _get_authorization_headers\n",
      "    self._credentials.before_request(\n",
      "AttributeError: 'str' object has no attribute 'before_request'\n",
      "ERROR:root:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x1128b9ac8>\" raised exception!\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/grpc/_plugin_wrapping.py\", line 77, in __call__\n",
      "    callback_state, callback))\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 77, in __call__\n",
      "    callback(self._get_authorization_headers(context), None)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 61, in _get_authorization_headers\n",
      "    self._credentials.before_request(\n",
      "AttributeError: 'str' object has no attribute 'before_request'\n",
      "ERROR:root:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x1128b9ac8>\" raised exception!\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/grpc/_plugin_wrapping.py\", line 77, in __call__\n",
      "    callback_state, callback))\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 77, in __call__\n",
      "    callback(self._get_authorization_headers(context), None)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 61, in _get_authorization_headers\n",
      "    self._credentials.before_request(\n",
      "AttributeError: 'str' object has no attribute 'before_request'\n",
      "ERROR:root:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x1128b9ac8>\" raised exception!\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/grpc/_plugin_wrapping.py\", line 77, in __call__\n",
      "    callback_state, callback))\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 77, in __call__\n",
      "    callback(self._get_authorization_headers(context), None)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 61, in _get_authorization_headers\n",
      "    self._credentials.before_request(\n",
      "AttributeError: 'str' object has no attribute 'before_request'\n",
      "ERROR:root:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x1128b9ac8>\" raised exception!\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/grpc/_plugin_wrapping.py\", line 77, in __call__\n",
      "    callback_state, callback))\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 77, in __call__\n",
      "    callback(self._get_authorization_headers(context), None)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 61, in _get_authorization_headers\n",
      "    self._credentials.before_request(\n",
      "AttributeError: 'str' object has no attribute 'before_request'\n",
      "ERROR:root:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x1128b9ac8>\" raised exception!\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/grpc/_plugin_wrapping.py\", line 77, in __call__\n",
      "    callback_state, callback))\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 77, in __call__\n",
      "    callback(self._get_authorization_headers(context), None)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 61, in _get_authorization_headers\n",
      "    self._credentials.before_request(\n",
      "AttributeError: 'str' object has no attribute 'before_request'\n",
      "ERROR:root:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x1128b9ac8>\" raised exception!\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/grpc/_plugin_wrapping.py\", line 77, in __call__\n",
      "    callback_state, callback))\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 77, in __call__\n",
      "    callback(self._get_authorization_headers(context), None)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 61, in _get_authorization_headers\n",
      "    self._credentials.before_request(\n",
      "AttributeError: 'str' object has no attribute 'before_request'\n",
      "ERROR:root:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x1128b9ac8>\" raised exception!\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/grpc/_plugin_wrapping.py\", line 77, in __call__\n",
      "    callback_state, callback))\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 77, in __call__\n",
      "    callback(self._get_authorization_headers(context), None)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 61, in _get_authorization_headers\n",
      "    self._credentials.before_request(\n",
      "AttributeError: 'str' object has no attribute 'before_request'\n",
      "ERROR:root:AuthMetadataPluginCallback \"<google.auth.transport.grpc.AuthMetadataPlugin object at 0x1128b9ac8>\" raised exception!\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/grpc/_plugin_wrapping.py\", line 77, in __call__\n",
      "    callback_state, callback))\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 77, in __call__\n",
      "    callback(self._get_authorization_headers(context), None)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/google/auth/transport/grpc.py\", line 61, in _get_authorization_headers\n",
      "    self._credentials.before_request(\n",
      "AttributeError: 'str' object has no attribute 'before_request'\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-38-30f7919e2368>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mtranscribe_file_with_enhanced_model\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'/Users/jannes/Documents/GitHub/compliance-ai-source-code/afi/samples/sample_testing.wav'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m<ipython-input-37-1c365e999167>\u001b[0m in \u001b[0;36mtranscribe_file_with_enhanced_model\u001b[0;34m(path)\u001b[0m\n\u001b[1;32m     23\u001b[0m         model='phone_call')\n\u001b[1;32m     24\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 25\u001b[0;31m     \u001b[0mresponse\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mclient\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrecognize\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mconfig\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0maudio\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     26\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     27\u001b[0m     \u001b[0;32mfor\u001b[0m \u001b[0mi\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mresult\u001b[0m \u001b[0;32min\u001b[0m \u001b[0menumerate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mresponse\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mresults\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/anaconda3/lib/python3.6/site-packages/google/cloud/speech_v1p1beta1/gapic/speech_client.py\u001b[0m in \u001b[0;36mrecognize\u001b[0;34m(self, config, audio, retry, timeout, metadata)\u001b[0m\n\u001b[1;32m    191\u001b[0m         )\n\u001b[1;32m    192\u001b[0m         return self._recognize(\n\u001b[0;32m--> 193\u001b[0;31m             request, retry=retry, timeout=timeout, metadata=metadata)\n\u001b[0m\u001b[1;32m    194\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    195\u001b[0m     def long_running_recognize(self,\n",
      "\u001b[0;32m/anaconda3/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py\u001b[0m in \u001b[0;36m__call__\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    137\u001b[0m             \u001b[0mkwargs\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'metadata'\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmetadata\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    138\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 139\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mwrapped_func\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    140\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    141\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/anaconda3/lib/python3.6/site-packages/google/api_core/retry.py\u001b[0m in \u001b[0;36mretry_wrapped_func\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    258\u001b[0m                 \u001b[0msleep_generator\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    259\u001b[0m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_deadline\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 260\u001b[0;31m                 \u001b[0mon_error\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mon_error\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    261\u001b[0m             )\n\u001b[1;32m    262\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/anaconda3/lib/python3.6/site-packages/google/api_core/retry.py\u001b[0m in \u001b[0;36mretry_target\u001b[0;34m(target, predicate, sleep_generator, deadline, on_error)\u001b[0m\n\u001b[1;32m    197\u001b[0m         _LOGGER.debug('Retrying due to {}, sleeping {:.1f}s ...'.format(\n\u001b[1;32m    198\u001b[0m             last_exc, sleep))\n\u001b[0;32m--> 199\u001b[0;31m         \u001b[0mtime\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msleep\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msleep\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    200\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    201\u001b[0m     \u001b[0;32mraise\u001b[0m \u001b[0mValueError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'Sleep generator stopped yielding sleep values.'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "transcribe_file_with_enhanced_model('/Users/jannes/Documents/GitHub/compliance-ai-source-code/afi/samples/sample_testing.wav')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
